#
# YAML Configuration File - routing
#     Routing for the application goes here
#
# Author      : Sam-Mauris Yong / mauris@hotmail.sg
# Copyright   : Copyright (c) 2010-2012, Sam-Mauris Yong
# License     : http://www.opensource.org/licenses/bsd-license New BSD License
#

---

display:
  rewrite: "/"
  method: "get"
  actual: "Alton\Map\Controller:display"

pinGenerator:
  rewrite: "/images/pin-{id}.png"
  method: "get"
  actual: "Alton\Api\Controller:generateImage"
  params:
    id: int

poll:
  rewrite: "/api/poll"
  method: "get"
  actual: "Alton\Map\Controller:polling"
  params:
    lastPoint: int

legend:
  rewrite: "/api/legend"
  method: "get"
  actual: "Alton\Map\Controller:legend"

dataSetCreate:
  rewrite: "/api/dataset/create"
  actual: "Alton\Api\Controller:create"
  params:
    title: any

dataSetPush:
  rewrite: "/api/dataset/push"
  actual: "Alton\Api\Controller:receive"
  params:
    latitude: double
    longitude: double
    set: alnum

session.reset:
  rewrite: "/reset"
  actual: "Alton\Session\Controller:reset"

...