#
# YAML Configuration File - routing
#     Routing for the application goes here
#
# Author      : Sam-Mauris Yong / mauris@hotmail.sg
# Copyright   : Copyright (c) 2010-2012, Sam-Mauris Yong
# License     : http://www.opensource.org/licenses/bsd-license New BSD License
#

---

display:
  rewrite: "/"
  method: "get"
  actual: "Map:display"

pinGenerator:
  rewrite: "/images/pin-{dataSet}.png"
  method: "get"
  actual: "Api:generateImage"
  params:
    dataSet: int

poll:
  rewrite: "/api/poll"
  method: "get"
  actual: "Map:polling"
  params:
    lastPoint: int
  
dataSetCreate:
  rewrite: "/api/dataset/create"
  actual: "Api:create"
  
dataSetPush:
  rewrite: "/api/dataset/push"
  actual: "Api:receive"
  params:
    latitude: double
    longitude: double
    dataSet: alnum
  
session.reset:
  rewrite: "/reset"
  actual: "Session:reset"

...