#
# YAML Configuration File - routing
#     Routing for the application goes here
#
# Author      : Sam-Mauris Yong / mauris@hotmail.sg
# Copyright   : Copyright (c) 2010-2012, Sam-Mauris Yong
# License     : http://www.opensource.org/licenses/bsd-license New BSD License
#

---

display:
  rewrite: "/"
  method: "get"
  actual: "Map:display"

poll:
  rewrite: "api/poll"
  method: "get"
  actual: "Map:polling"
  
receive:
  rewrite: "/api/dataset/create"
  actual: "Api:create"
  
receive:
  rewrite: "/api/dataset/push"
  actual: "Api:receive"
  
session.reset:
  rewrite: "/reset"
  actual: "Session:reset"

...